# Generated by Django 4.1.7 on 2023-03-17 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_jobinterview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
