# Generated by Django 4.1.7 on 2023-03-17 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_jobinterview_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='number_of_questions',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
