# Generated by Django 4.1.7 on 2023-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0005_question_employee_alter_question_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
