# Generated by Django 4.1.7 on 2023-03-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_jobinterview_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinterview',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
